**Mayur Pralhad Musale**

**Registration ID : SIRSS1240**

**Assignment No : 11    (Leaf Classification)**

In [1]:
import pandas as pd
import numpy as np

In [2]:
train_data = pd.read_csv('train.csv.zip', index_col ='id')
test_data = pd.read_csv('test.csv.zip')

In [3]:
test_ids = test_data.id
test_data = test_data.drop(['id'], axis =1)

In [4]:
#Data Preprocessing
train_data.head()

,species,margin1,margin2,margin3,margin4,margin5,margin6,margin7,margin8,margin9,...,texture55,texture56,texture57,texture58,texture59,texture60,texture61,texture62,texture63,texture64
id,,,,,,,,,,,,,,,,,,,,,
1,Acer_Opalus,0.007812,0.023438,0.023438,0.003906,0.011719,0.009766,0.027344,0.0,0.001953,...,0.007812,0.000000,0.002930,0.002930,0.035156,0.0,0.0,0.004883,0.000000,0.025391
2,Pterocarya_Stenoptera,0.005859,0.000000,0.031250,0.015625,0.025391,0.001953,0.019531,0.0,0.000000,...,0.000977,0.000000,0.000000,0.000977,0.023438,0.0,0.0,0.000977,0.039062,0.022461
3,Quercus_Hartwissiana,0.005859,0.009766,0.019531,0.007812,0.003906,0.005859,0.068359,0.0,0.000000,...,0.154300,0.000000,0.005859,0.000977,0.007812,0.0,0.0,0.000000,0.020508,0.002930
5,Tilia_Tomentosa,0.000000,0.003906,0.023438,0.005859,0.021484,0.019531,0.023438,0.0,0.013672,...,0.000000,0.000977,0.000000,0.000000,0.020508,0.0,0.0,0.017578,0.000000,0.047852
6,Quercus_Variabilis,0.005859,0.003906,0.048828,0.009766,0.013672,0.015625,0.005859,0.0,0.000000,...,0.096680,0.000000,0.021484,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.031250

In [5]:
train_data.tail()

,species,margin1,margin2,margin3,margin4,margin5,margin6,margin7,margin8,margin9,...,texture55,texture56,texture57,texture58,texture59,texture60,texture61,texture62,texture63,texture64
id,,,,,,,,,,,,,,,,,,,,,
1575,Magnolia_Salicifolia,0.060547,0.119140,0.007812,0.003906,0.000000,0.148440,0.017578,0.0,0.001953,...,0.242190,0.000000,0.034180,0.000000,0.010742,0.000000,0.000000,0.000000,0.000000,0.018555
1578,Acer_Pictum,0.001953,0.003906,0.021484,0.107420,0.001953,0.000000,0.000000,0.0,0.029297,...,0.170900,0.000000,0.018555,0.000000,0.011719,0.000000,0.000000,0.000977,0.000000,0.021484
1581,Alnus_Maximowiczii,0.001953,0.003906,0.000000,0.021484,0.078125,0.003906,0.007812,0.0,0.003906,...,0.004883,0.000977,0.004883,0.027344,0.016602,0.007812,0.000000,0.027344,0.000000,0.001953
1582,Quercus_Rubra,0.000000,0.000000,0.046875,0.056641,0.009766,0.000000,0.000000,0.0,0.037109,...,0.083008,0.030273,0.000977,0.002930,0.014648,0.000000,0.041992,0.000000,0.001953,0.002930
1584,Quercus_Afares,0.023438,0.019531,0.031250,0.015625,0.005859,0.019531,0.035156,0.0,0.003906,...,0.000000,0.000000,0.002930,0.000000,0.012695,0.000000,0.000000,0.023438,0.025391,0.022461

In [6]:
test_data.isnull().any().sum()

0

In [7]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 990 entries, 1 to 1584
Columns: 193 entries, species to texture64
dtypes: float64(192), object(1)
memory usage: 1.5+ MB

In [8]:
test_data.shape

(594, 192)

In [9]:
train_data.describe()

,margin1,margin2,margin3,margin4,margin5,margin6,margin7,margin8,margin9,margin10,...,texture55,texture56,texture57,texture58,texture59,texture60,texture61,texture62,texture63,texture64
count,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000,...,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000,990.000000
mean,0.017412,0.028539,0.031988,0.023280,0.014264,0.038579,0.019202,0.001083,0.007167,0.018639,...,0.036501,0.005024,0.015944,0.011586,0.016108,0.014017,0.002688,0.020291,0.008989,0.019420
std,0.019739,0.038855,0.025847,0.028411,0.018390,0.052030,0.017511,0.002743,0.008933,0.016071,...,0.063403,0.019321,0.023214,0.025040,0.015335,0.060151,0.011415,0.039040,0.013791,0.022768
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.001953,0.001953,0.013672,0.005859,0.001953,0.000000,0.005859,0.000000,0.001953,0.005859,...,0.000000,0.000000,0.000977,0.000000,0.004883,0.000000,0.000000,0.000000,0.000000,0.000977
50%,0.009766,0.011719,0.025391,0.013672,0.007812,0.015625,0.015625,0.000000,0.005859,0.015625,...,0.004883,0.000000,0.005859,0.000977,0.012695,0.000000,0.000000,0.003906,0.002930,0.011719
75%,0.025391,0.041016,0.044922,0.029297,0.017578,0.056153,0.029297,0.000000,0.007812,0.027344,...,0.043701,0.000000,0.022217,0.009766,0.021484,0.000000,0.000000,0.023438,0.012695,0.029297
max,0.087891,0.205080,0.156250,0.169920,0.111330,0.310550,0.091797,0.031250,0.076172,0.097656,...,0.429690,0.202150,0.172850,0.200200,0.106450,0.578130,0.151370,0.375980,0.086914,0.141600

In [10]:
train_data.describe().T

,count,mean,std,min,25%,50%,75%,max
margin1,990.0,0.017412,0.019739,0.0,0.001953,0.009766,0.025391,0.087891
margin2,990.0,0.028539,0.038855,0.0,0.001953,0.011719,0.041016,0.205080
margin3,990.0,0.031988,0.025847,0.0,0.013672,0.025391,0.044922,0.156250
margin4,990.0,0.023280,0.028411,0.0,0.005859,0.013672,0.029297,0.169920
margin5,990.0,0.014264,0.018390,0.0,0.001953,0.007812,0.017578,0.111330
...,...,...,...,...,...,...,...,...
texture60,990.0,0.014017,0.060151,0.0,0.000000,0.000000,0.000000,0.578130
texture61,990.0,0.002688,0.011415,0.0,0.000000,0.000000,0.000000,0.151370
texture62,990.0,0.020291,0.039040,0.0,0.000000,0.003906,0.023438,0.375980
texture63,990.0,0.008989,0.013791,0.0,0.000000,0.002930,0.012695,0.086914
texture64,990.0,0.019420,0.022768,0.0,0.000977,0.011719,0.029297,0.141600

In [11]:
test_data.describe()

,margin1,margin2,margin3,margin4,margin5,margin6,margin7,margin8,margin9,margin10,...,texture55,texture56,texture57,texture58,texture59,texture60,texture61,texture62,texture63,texture64
count,594.000000,594.000000,594.000000,594.000000,594.000000,594.000000,594.000000,594.000000,594.000000,594.000000,...,594.000000,594.000000,594.000000,594.000000,594.000000,594.000000,594.000000,594.000000,594.000000,594.000000
mean,0.017562,0.028425,0.031858,0.022556,0.014527,0.037497,0.019222,0.001085,0.007092,0.018798,...,0.035291,0.005923,0.015033,0.011762,0.015881,0.011217,0.002617,0.019975,0.009389,0.020970
std,0.019585,0.038351,0.025719,0.028797,0.018029,0.051372,0.017122,0.002697,0.009515,0.016229,...,0.064482,0.026934,0.022318,0.024771,0.014898,0.052530,0.011204,0.034704,0.013457,0.023407
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.001953,0.001953,0.013672,0.005859,0.001953,0.000000,0.005859,0.000000,0.001953,0.005859,...,0.000000,0.000000,0.000977,0.000000,0.004883,0.000000,0.000000,0.000000,0.000000,0.000977
50%,0.009766,0.010743,0.023438,0.013672,0.007812,0.013672,0.015625,0.000000,0.005859,0.015625,...,0.003906,0.000000,0.005859,0.001953,0.012695,0.000000,0.000000,0.003418,0.002930,0.013184
75%,0.028809,0.041016,0.042969,0.027344,0.019531,0.056641,0.029297,0.000000,0.007812,0.027344,...,0.038086,0.000000,0.019531,0.010498,0.022461,0.000000,0.000000,0.022461,0.014648,0.032227
max,0.085938,0.189450,0.167970,0.164060,0.093750,0.271480,0.087891,0.021484,0.083984,0.083984,...,0.353520,0.441410,0.153320,0.177730,0.083984,0.606450,0.123050,0.247070,0.086914,0.149410

In [12]:
test_data.describe().T

,count,mean,std,min,25%,50%,75%,max
margin1,594.0,0.017562,0.019585,0.0,0.001953,0.009766,0.028809,0.085938
margin2,594.0,0.028425,0.038351,0.0,0.001953,0.010743,0.041016,0.189450
margin3,594.0,0.031858,0.025719,0.0,0.013672,0.023438,0.042969,0.167970
margin4,594.0,0.022556,0.028797,0.0,0.005859,0.013672,0.027344,0.164060
margin5,594.0,0.014527,0.018029,0.0,0.001953,0.007812,0.019531,0.093750
...,...,...,...,...,...,...,...,...
texture60,594.0,0.011217,0.052530,0.0,0.000000,0.000000,0.000000,0.606450
texture61,594.0,0.002617,0.011204,0.0,0.000000,0.000000,0.000000,0.123050
texture62,594.0,0.019975,0.034704,0.0,0.000000,0.003418,0.022461,0.247070
texture63,594.0,0.009389,0.013457,0.0,0.000000,0.002930,0.014648,0.086914
texture64,594.0,0.020970,0.023407,0.0,0.000977,0.013184,0.032227,0.149410

In [13]:
train_data['species'].nunique()

99

In [14]:
x = train_data.drop('species',axis=1)
y = train_data['species']

In [15]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y_fit = encoder.fit(train_data['species'])
y_label = y_fit.transform(train_data['species']) 
classes = list(y_fit.classes_) 
classes

['Acer_Capillipes',
 'Acer_Circinatum',
 'Acer_Mono',
 'Acer_Opalus',
 'Acer_Palmatum',
 'Acer_Pictum',
 'Acer_Platanoids',
 'Acer_Rubrum',
 'Acer_Rufinerve',
 'Acer_Saccharinum',
 'Alnus_Cordata',
 'Alnus_Maximowiczii',
 'Alnus_Rubra',
 'Alnus_Sieboldiana',
 'Alnus_Viridis',
 'Arundinaria_Simonii',
 'Betula_Austrosinensis',
 'Betula_Pendula',
 'Callicarpa_Bodinieri',
 'Castanea_Sativa',
 'Celtis_Koraiensis',
 'Cercis_Siliquastrum',
 'Cornus_Chinensis',
 'Cornus_Controversa',
 'Cornus_Macrophylla',
 'Cotinus_Coggygria',
 'Crataegus_Monogyna',
 'Cytisus_Battandieri',
 'Eucalyptus_Glaucescens',
 'Eucalyptus_Neglecta',
 'Eucalyptus_Urnigera',
 'Fagus_Sylvatica',
 'Ginkgo_Biloba',
 'Ilex_Aquifolium',
 'Ilex_Cornuta',
 'Liquidambar_Styraciflua',
 'Liriodendron_Tulipifera',
 'Lithocarpus_Cleistocarpus',
 'Lithocarpus_Edulis',
 'Magnolia_Heptapeta',
 'Magnolia_Salicifolia',
 'Morus_Nigra',
 'Olea_Europaea',
 'Phildelphus',
 'Populus_Adenopoda',
 'Populus_Grandidentata',
 'Populus_Nigra',
 'Prunus_Avium',
 'Prunus_X_Shmittii',
 'Pterocarya_Stenoptera',
 'Quercus_Afares',
 'Quercus_Agrifolia',
 'Quercus_Alnifolia',
 'Quercus_Brantii',
 'Quercus_Canariensis',
 'Quercus_Castaneifolia',
 'Quercus_Cerris',
 'Quercus_Chrysolepis',
 'Quercus_Coccifera',
 'Quercus_Coccinea',
 'Quercus_Crassifolia',
 'Quercus_Crassipes',
 'Quercus_Dolicholepis',
 'Quercus_Ellipsoidalis',
 'Quercus_Greggii',
 'Quercus_Hartwissiana',
 'Quercus_Ilex',
 'Quercus_Imbricaria',
 'Quercus_Infectoria_sub',
 'Quercus_Kewensis',
 'Quercus_Nigra',
 'Quercus_Palustris',
 'Quercus_Phellos',
 'Quercus_Phillyraeoides',
 'Quercus_Pontica',
 'Quercus_Pubescens',
 'Quercus_Pyrenaica',
 'Quercus_Rhysophylla',
 'Quercus_Rubra',
 'Quercus_Semecarpifolia',
 'Quercus_Shumardii',
 'Quercus_Suber',
 'Quercus_Texana',
 'Quercus_Trojana',
 'Quercus_Variabilis',
 'Quercus_Vulcanica',
 'Quercus_x_Hispanica',
 'Quercus_x_Turneri',
 'Rhododendron_x_Russellianum',
 'Salix_Fragilis',
 'Salix_Intergra',
 'Sorbus_Aria',
 'Tilia_Oliveri',
 'Tilia_Platyphyllos',
 'Tilia_Tomentosa',
 'Ulmus_Bergmanniana',
 'Viburnum_Tinus',
 'Viburnum_x_Rhytidophylloides',
 'Zelkova_Serrata']

In [16]:
from sklearn.model_selection import  train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y_label, test_size = 0.2, random_state =1)

In [17]:
#Model Building
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 40)
classifier.fit(x_train, y_train)

RandomForestClassifier(n_estimators=40)

In [18]:
from sklearn.metrics import classification_report
predictions = classifier.predict(x_test)
print (classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         4
           1       1.00      1.00      1.00         1
           2       1.00      1.00      1.00         2
           3       1.00      1.00      1.00         3
           4       1.00      1.00      1.00         3
           5       1.00      1.00      1.00         2
           6       1.00      1.00      1.00         3
           7       1.00      1.00      1.00         1
           8       1.00      1.00      1.00         1
           9       1.00      1.00      1.00         3
          10       0.50      1.00      0.67         1
          11       1.00      1.00      1.00         3
          12       1.00      1.00      1.00         3
          13       1.00      1.00      1.00         2
          14       1.00      1.00      1.00         2
          15       1.00      1.00      1.00         2
          16       1.00      1.00      1.00         2
          17       1.00      1.00      1.00         1
          18       1.00      1.00      1.00         3
          19       1.00      1.00      1.00         2
          20       1.00      1.00      1.00         5
          21       1.00      1.00      1.00         3
          22       1.00      1.00      1.00         3
          23       1.00      1.00      1.00         3
          24       1.00      1.00      1.00         1
          25       1.00      1.00      1.00         1
          26       1.00      1.00      1.00         3
          27       1.00      1.00      1.00         1
          28       1.00      0.67      0.80         3
          29       0.00      0.00      0.00         0
          30       0.67      1.00      0.80         2
          31       1.00      1.00      1.00         1
          32       1.00      1.00      1.00         2
          33       1.00      1.00      1.00         5
          34       1.00      1.00      1.00         1
          36       1.00      1.00      1.00         2
          37       1.00      1.00      1.00         2
          39       1.00      1.00      1.00         3
          40       1.00      1.00      1.00         2
          41       1.00      1.00      1.00         4
          42       1.00      1.00      1.00         2
          43       1.00      1.00      1.00         1
          44       1.00      1.00      1.00         1
          45       1.00      1.00      1.00         2
          46       1.00      1.00      1.00         2
          47       1.00      1.00      1.00         2
          48       1.00      1.00      1.00         3
          49       1.00      0.50      0.67         2
          50       1.00      1.00      1.00         2
          52       1.00      1.00      1.00         1
          53       1.00      1.00      1.00         3
          54       1.00      0.83      0.91         6
          55       0.50      1.00      0.67         1
          56       1.00      1.00      1.00         1
          58       1.00      1.00      1.00         1
          59       1.00      1.00      1.00         3
          60       1.00      1.00      1.00         2
          61       1.00      1.00      1.00         5
          62       1.00      1.00      1.00         2
          63       0.75      1.00      0.86         3
          64       1.00      0.50      0.67         2
          65       1.00      1.00      1.00         4
          66       1.00      1.00      1.00         2
          68       0.00      0.00      0.00         1
          69       1.00      0.50      0.67         2
          70       1.00      1.00      1.00         2
          71       1.00      0.50      0.67         2
          72       1.00      1.00      1.00         1
          73       1.00      1.00      1.00         1
          74       1.00      1.00      1.00         1
          75       1.00      1.00      1.00         1
          76       1.00      1.00      1.00         1
          77       1.00      1.00      1.00         2
          78       1.00      1.00      1.00         2
          79       1.00      1.00      1.00         1
          81       0.00      0.00      0.00         1
          82       1.00      1.00      1.00         2
          83       1.00      1.00      1.00         2
          84       0.50      1.00      0.67         1
          85       1.00      1.00      1.00         1
          86       1.00      1.00      1.00         2
          87       1.00      1.00      1.00         2
          88       1.00      1.00      1.00         1
          89       1.00      1.00      1.00         3
          90       1.00      1.00      1.00         2
          91       1.00      1.00      1.00         1
          92       0.67      1.00      0.80         2
          93       1.00      1.00      1.00         3
          94       1.00      1.00      1.00         3
          95       1.00      1.00      1.00         4
          96       1.00      1.00      1.00         3
          97       1.00      1.00      1.00         2
          98       1.00      1.00      1.00         2

    accuracy                           0.96       198
   macro avg       0.94      0.94      0.93       198
weighted avg       0.97      0.96      0.96       198

C:\Users\user\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [19]:
final_predictions = classifier.predict_proba(test_data)

In [20]:
submission = pd.DataFrame(final_predictions, columns=classes)
submission.insert(0, 'id', test_ids)
submission.reset_index()

,index,id,Acer_Capillipes,Acer_Circinatum,Acer_Mono,Acer_Opalus,Acer_Palmatum,Acer_Pictum,Acer_Platanoids,Acer_Rubrum,...,Salix_Fragilis,Salix_Intergra,Sorbus_Aria,Tilia_Oliveri,Tilia_Platyphyllos,Tilia_Tomentosa,Ulmus_Bergmanniana,Viburnum_Tinus,Viburnum_x_Rhytidophylloides,Zelkova_Serrata
0,0,4,0.000,0.000,0.000,0.000,0.000,0.00,0.000,0.000,...,0.000,0.0,0.000,0.0,0.000,0.000,0.000,0.000,0.0,0.000
1,1,7,0.000,0.000,0.025,0.075,0.000,0.00,0.050,0.000,...,0.000,0.0,0.000,0.0,0.000,0.050,0.000,0.000,0.0,0.000
2,2,9,0.000,0.700,0.000,0.000,0.025,0.00,0.000,0.000,...,0.000,0.0,0.025,0.0,0.000,0.000,0.000,0.000,0.0,0.000
3,3,12,0.000,0.075,0.000,0.025,0.000,0.00,0.000,0.000,...,0.000,0.0,0.000,0.0,0.000,0.025,0.050,0.025,0.0,0.025
4,4,13,0.025,0.025,0.000,0.000,0.000,0.00,0.000,0.000,...,0.000,0.0,0.000,0.0,0.000,0.025,0.050,0.000,0.0,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
589,589,1576,0.000,0.600,0.000,0.000,0.025,0.00,0.000,0.000,...,0.000,0.0,0.000,0.0,0.000,0.000,0.000,0.000,0.0,0.025
590,590,1577,0.000,0.000,0.000,0.025,0.000,0.00,0.000,0.025,...,0.000,0.0,0.025,0.0,0.025,0.000,0.025,0.000,0.0,0.100
591,591,1579,0.000,0.000,0.000,0.000,0.000,0.05,0.000,0.000,...,0.000,0.0,0.025,0.0,0.000,0.000,0.000,0.000,0.0,0.000
592,592,1580,0.000,0.000,0.000,0.000,0.025,0.00,0.025,0.000,...,0.025,0.0,0.000,0.0,0.000,0.050,0.000,0.000,0.0,0.000
593,593,1583,0.000,0.000,0.000,0.000,0.025,0.00,0.000,0.000,...,0.000,0.0,0.000,0.0,0.000,0.000,0.025,0.000,0.0,0.000

In [21]:
submission.to_csv('result.csv')

In [22]:
results_data = pd.read_csv('result.csv')

In [23]:
results_data.head(10)

,Unnamed: 0,id,Acer_Capillipes,Acer_Circinatum,Acer_Mono,Acer_Opalus,Acer_Palmatum,Acer_Pictum,Acer_Platanoids,Acer_Rubrum,...,Salix_Fragilis,Salix_Intergra,Sorbus_Aria,Tilia_Oliveri,Tilia_Platyphyllos,Tilia_Tomentosa,Ulmus_Bergmanniana,Viburnum_Tinus,Viburnum_x_Rhytidophylloides,Zelkova_Serrata
0,0,4,0.000,0.000,0.000,0.000,0.000,0.0,0.00,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000
1,1,7,0.000,0.000,0.025,0.075,0.000,0.0,0.05,0.000,...,0.000,0.000,0.000,0.000,0.0,0.050,0.000,0.000,0.0,0.000
2,2,9,0.000,0.700,0.000,0.000,0.025,0.0,0.00,0.000,...,0.000,0.000,0.025,0.000,0.0,0.000,0.000,0.000,0.0,0.000
3,3,12,0.000,0.075,0.000,0.025,0.000,0.0,0.00,0.000,...,0.000,0.000,0.000,0.000,0.0,0.025,0.050,0.025,0.0,0.025
4,4,13,0.025,0.025,0.000,0.000,0.000,0.0,0.00,0.000,...,0.000,0.000,0.000,0.000,0.0,0.025,0.050,0.000,0.0,0.000
5,5,16,0.000,0.000,0.000,0.175,0.000,0.0,0.00,0.000,...,0.025,0.000,0.000,0.000,0.0,0.075,0.025,0.050,0.0,0.000
6,6,19,0.000,0.000,0.000,0.475,0.000,0.0,0.00,0.000,...,0.000,0.000,0.000,0.000,0.0,0.050,0.000,0.025,0.0,0.025
7,7,23,0.000,0.000,0.000,0.025,0.000,0.0,0.00,0.000,...,0.000,0.025,0.000,0.025,0.0,0.000,0.000,0.025,0.0,0.000
8,8,24,0.000,0.000,0.000,0.000,0.000,0.0,0.00,0.000,...,0.000,0.000,0.000,0.000,0.0,0.000,0.000,0.000,0.0,0.000
9,9,28,0.000,0.000,0.000,0.000,0.000,0.0,0.00,0.025,...,0.000,0.000,0.025,0.000,0.0,0.050,0.000,0.000,0.0,0.000